#!/usr/bin/env node
// JSON Schema -> per-language types for fiducia.cloud.
//
//   node src/generate.mjs          # write generated/<lang>/...
//   node src/generate.mjs --check  # verify generated files are up to date (CI)
//
// JSON Schema (schema/*.schema.json) is the source of truth. Generated files are
// adapters only — never hand-edit them. Adding a language is one entry in
// EMITTERS; adding a type is one entry in a schema file + schema/index.json.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaDir = path.join(root, "schema");
const genDir = path.join(root, "generated");

const BANNER = "AUTOGENERATED by src/generate.mjs — do not edit by hand; edit schema/ and regenerate.";

// --- parse schemas into a flat list of object types ---------------------------

function loadTypes() {
  const index = JSON.parse(fs.readFileSync(path.join(schemaDir, "index.json"), "utf8"));
  const types = [];
  for (const file of index.schemas) {
    const doc = JSON.parse(fs.readFileSync(path.join(schemaDir, file), "utf8"));
    for (const [name, def] of Object.entries(doc.$defs || {})) {
      const required = new Set(def.required || []);
      const props = Object.entries(def.properties || {}).map(([pname, pschema]) => ({
        name: pname,
        schema: pschema,
        required: required.has(pname),
        description: pschema.description || "",
      }));
      types.push({ name, description: def.description || "", props });
    }
  }
  return types;
}

const refName = (s) => (s.$ref ? s.$ref.split("/").pop() : null);
const pascal = (s) => s.split("_").map((w) => (w ? w[0].toUpperCase() + w.slice(1) : "")).join("");

// --- per-language type resolvers ---------------------------------------------

function rustType(s) {
  const r = refName(s);
  if (r) return r;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "i64";
    case "number": return "f64";
    case "boolean": return "bool";
    case "array": return `Vec<${rustType(s.items || {})}>`;
    default: return "serde_json::Value";
  }
}
function tsType(s) {
  const r = refName(s);
  if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(s.items || {})}[]`;
    default: return "Record<string, unknown>";
  }
}
function pyType(s) {
  const r = refName(s);
  if (r) return r;
  switch (s.type) {
    case "string": return "str";
    case "integer": return "int";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return `List[${pyType(s.items || {})}]`;
    default: return "dict";
  }
}
function goType(s) {
  const r = refName(s);
  if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": return "int64";
    case "number": return "float64";
    case "boolean": return "bool";
    case "array": return `[]${goType(s.items || {})}`;
    default: return "map[string]any";
  }
}

// --- emitters: type[] -> { relpath: content } --------------------------------

function emitRust(types) {
  // Field types use fully-qualified `serde_json::Value`, so no extra `use` is
  // needed (serde_json is a dependency of the generated crate).
  const out = [`// ${BANNER}`, "", "use serde::{Deserialize, Serialize};", ""];
  for (const t of types) {
    if (t.description) out.push(`/// ${t.description}`);
    out.push("#[derive(Debug, Clone, Serialize, Deserialize)]", `pub struct ${t.name} {`);
    for (const p of t.props) {
      if (p.description) out.push(`    /// ${p.description}`);
      const ty = rustType(p.schema);
      if (p.required) {
        out.push(`    pub ${p.name}: ${ty},`);
      } else {
        out.push(`    #[serde(default, skip_serializing_if = "Option::is_none")]`, `    pub ${p.name}: Option<${ty}>,`);
      }
    }
    out.push("}", "");
  }
  const cargo = `[package]
name = "fiducia-interfaces"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for fiducia.cloud (see fiducia-interfaces)."

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
  return { "rust/src/lib.rs": out.join("\n"), "rust/Cargo.toml": cargo };
}

function emitTs(types) {
  const out = [`// ${BANNER}`, ""];
  for (const t of types) {
    if (t.description) out.push(`/** ${t.description} */`);
    out.push(`export type ${t.name} = {`);
    for (const p of t.props) {
      if (p.description) out.push(`  /** ${p.description} */`);
      out.push(`  ${p.name}${p.required ? "" : "?"}: ${tsType(p.schema)};`);
    }
    out.push("};", "");
  }
  return { "typescript/index.ts": out.join("\n") };
}

function emitPython(types) {
  const out = [`# ${BANNER}`, "from __future__ import annotations", "from dataclasses import dataclass", "from typing import List, Optional", ""];
  for (const t of types) {
    out.push("@dataclass");
    out.push(`class ${t.name}:`);
    if (t.description) out.push(`    """${t.description}"""`);
    // required first, then optional (dataclass ordering rule)
    const ordered = [...t.props].sort((a, b) => Number(b.required) - Number(a.required));
    if (ordered.length === 0) out.push("    pass");
    for (const p of ordered) {
      const ty = pyType(p.schema);
      out.push(p.required ? `    ${p.name}: ${ty}` : `    ${p.name}: Optional[${ty}] = None`);
    }
    out.push("");
  }
  return { "python/fiducia_interfaces.py": out.join("\n") };
}

function emitGo(types) {
  const out = [`// ${BANNER}`, "", "package fiducia", ""];
  for (const t of types) {
    if (t.description) out.push(`// ${t.name}: ${t.description}`);
    out.push(`type ${t.name} struct {`);
    for (const p of t.props) {
      if (p.description) out.push(`\t// ${p.description}`);
      const ty = goType(p.schema);
      const tag = p.required ? `json:"${p.name}"` : `json:"${p.name},omitempty"`;
      out.push(`\t${pascal(p.name)} ${p.required ? "" : "*"}${ty} \`${tag}\``);
    }
    out.push("}", "");
  }
  return { "go/interfaces.go": out.join("\n") };
}

const EMITTERS = {
  rust: emitRust,
  typescript: emitTs,
  python: emitPython,
  go: emitGo,
  // TODO(client langs): dart, ruby, java, csharp, php, elixir — same shape as
  // above, one render fn each. The fiducia-clients HTTP wrappers consume these.
};

// --- run ---------------------------------------------------------------------

function build() {
  const types = loadTypes();
  const files = {};
  for (const emit of Object.values(EMITTERS)) {
    Object.assign(files, emit(types));
  }
  return files;
}

function main() {
  const check = process.argv.includes("--check");
  const files = build();
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(genDir, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) {
        console.error(`drift: ${rel}`);
        drift++;
      }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) {
    console.error(`${drift} file(s) out of date — run: node src/generate.mjs`);
    process.exit(1);
  }
  if (check) console.log("generated files up to date");
}

main();
