#!/usr/bin/env node
// JSON Schema -> per-language types for fiducia.cloud.
//
//   node src/generate.mjs          # write generated/<lang>/...
//   node src/generate.mjs --check  # verify generated files are up to date (CI)
//   node src/generate.mjs --only=typescript/index.ts
//                                  # write one generated file
//
// JSON Schema (schema/*.schema.json) is the source of truth. Generated files are
// adapters only — never hand-edit them. Adding a language is one entry in
// EMITTERS; adding a type is one entry in a schema file + schema/index.json.
//
// Hardened: validates the index + every schema, rejects duplicate type names and
// dangling $refs, enforces snake_case field names, sanitizes doc comments,
// raw-escapes Rust keyword fields, and emits typed enums for string `enum`s.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaDir = path.join(root, "schema");
const genDir = path.join(root, "generated");

const BANNER = "AUTOGENERATED by src/generate.mjs — do not edit by hand; edit schema/ and regenerate.";

class GenError extends Error {}
const fail = (msg) => { throw new GenError(msg); };

// --- helpers -----------------------------------------------------------------

const oneLine = (s) => String(s || "").replace(/\s+/g, " ").trim();
const pascal = (s) => s.split(/[_\-\s]+/).map((w) => (w ? w[0].toUpperCase() + w.slice(1) : "")).join("");
// Comment-escapers so a description can never break the generated file.
const cLine = (s) => oneLine(s);                                  // // and /// and #
const cBlock = (s) => oneLine(s).replace(/\*\//g, "*\\/");        // /** ... */
const pyDoc = (s) => oneLine(s).replace(/"""/g, "'''").replace(/\\/g, "\\\\"); // """ ... """

const RUST_KEYWORDS = new Set([
  "as","break","const","continue","crate","dyn","else","enum","extern","false","fn","for","if","impl",
  "in","let","loop","match","mod","move","mut","pub","ref","return","self","static","struct","super",
  "trait","true","type","unsafe","use","where","while","async","await","box","union",
]);
const PYTHON_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
  "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
  "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
  "try", "while", "with", "yield",
]);
const FIELD_RE = /^[a-z][a-z0-9_]*$/;

const refName = (s) => (s && s.$ref ? s.$ref.split("/").pop() : null);
const isStringEnum = (s) => s && s.type === "string" && Array.isArray(s.enum) && s.enum.length > 0;
const isNullable = (s) => s && Array.isArray(s.type) && s.type.includes("null");
const nonNullSchema = (s) => {
  if (!isNullable(s)) return s;
  const candidates = s.type.filter((candidate) => candidate !== "null");
  if (candidates.length !== 1) fail("nullable schema must include exactly one non-null type");
  const [type] = candidates;
  return { ...s, type };
};
const mapValueSchema = (s) => (
  s && s.type === "object" && s.additionalProperties && typeof s.additionalProperties === "object"
    ? s.additionalProperties
    : null
);
const enumTypeName = (typeName, fieldName) => `${typeName}${pascal(fieldName)}`;

// --- load + validate ----------------------------------------------------------

function loadTypes() {
  const indexPath = path.join(schemaDir, "index.json");
  if (!fs.existsSync(indexPath)) fail(`missing ${indexPath}`);
  let index;
  try { index = JSON.parse(fs.readFileSync(indexPath, "utf8")); }
  catch (e) { fail(`schema/index.json is not valid JSON: ${e.message}`); }
  if (!Array.isArray(index.schemas)) fail("schema/index.json must have a `schemas` array");

  const types = [];
  const seen = new Map(); // type name -> source file (duplicate detection)

  for (const file of index.schemas) {
    if (typeof file !== "string" || !file.endsWith(".schema.json")) {
      fail(`schema/index.json entry is not a *.schema.json file: ${JSON.stringify(file)}`);
    }
    const abs = path.join(schemaDir, file);
    if (!fs.existsSync(abs)) fail(`schema/index.json lists ${file} but it does not exist`);
    let doc;
    try { doc = JSON.parse(fs.readFileSync(abs, "utf8")); }
    catch (e) { fail(`${file} is not valid JSON: ${e.message}`); }
    if (!doc.$defs || typeof doc.$defs !== "object") fail(`${file} has no $defs object`);

    for (const [name, def] of Object.entries(doc.$defs)) {
      if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(`${file}: $def name must be PascalCase: ${name}`);
      if (seen.has(name)) fail(`duplicate type name "${name}" in ${file} and ${seen.get(name)}`);
      seen.set(name, file);
      const required = new Set(def.required || []);
      const props = Object.entries(def.properties || {}).map(([pname, pschema]) => {
        if (!FIELD_RE.test(pname)) fail(`${file}:${name}: property "${pname}" must be snake_case (${FIELD_RE})`);
        return {
          name: pname,
          schema: pschema,
          required: required.has(pname),
          description: pschema.description || "",
          deprecated: pschema.deprecated === true,
        };
      });
      // Keep the complete definition as well as the flattened property list.
      // Emitters use `props`; contract tests use `schema` to exercise bounds,
      // patterns, and composition keywords from the same source of truth.
      types.push({
        name,
        description: def.description || "",
        deprecated: def.deprecated === true,
        props,
        schema: def,
        source: file,
      });
    }
  }

  // Validate every $ref points at a known type.
  const known = new Set(types.map((t) => t.name));
  for (const t of types) {
    for (const p of t.props) {
      for (const s of [p.schema, p.schema && p.schema.items, p.schema && p.schema.additionalProperties]) {
        const r = refName(s);
        if (r && !known.has(r)) fail(`${t.source}:${t.name}.${p.name}: $ref to unknown type "${r}"`);
      }
    }
  }
  return types;
}

// Collect distinct enum types referenced by fields (for languages with enums).
function collectEnums(types) {
  const enums = new Map(); // enumName -> values[]
  for (const t of types) {
    for (const p of t.props) {
      if (isStringEnum(p.schema)) enums.set(enumTypeName(t.name, p.name), p.schema.enum.slice());
    }
  }
  return enums;
}

// --- per-language scalar resolvers (non-enum) --------------------------------

function rustType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  const mapValue = mapValueSchema(s); if (mapValue) return `std::collections::BTreeMap<String, ${rustType(mapValue)}>`;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "i64";
    case "number": return "f64";
    case "boolean": return "bool";
    case "array": return `Vec<${rustType(s.items || {})}>`;
    default: return "serde_json::Value";
  }
}
function tsType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  const mapValue = mapValueSchema(s); if (mapValue) return `Record<string, ${tsType(mapValue)}>`;
  switch (s.type) {
    case "string": return "string";
    case "integer": case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(s.items || {})}[]`;
    default: return "Record<string, unknown>";
  }
}
function pyType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  const mapValue = mapValueSchema(s); if (mapValue) return `Dict[str, ${pyType(mapValue)}]`;
  switch (s.type) {
    case "string": return "str";
    case "integer": return "int";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return `List[${pyType(s.items || {})}]`;
    default: return "dict";
  }
}
function goType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  const mapValue = mapValueSchema(s); if (mapValue) return `map[string]${goType(mapValue)}`;
  switch (s.type) {
    case "string": return "string";
    case "integer": return "int64";
    case "number": return "float64";
    case "boolean": return "bool";
    case "array": return `[]${goType(s.items || {})}`;
    default: return "map[string]any";
  }
}
function dartType(s) {
  s = nonNullSchema(s);
  const r = refName(s); if (r) return r;
  const mapValue = mapValueSchema(s); if (mapValue) return `Map<String, ${dartType(mapValue)}>`;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "int";
    case "number": return "num";
    case "boolean": return "bool";
    case "array": return `List<${dartType(s.items || {})}>`;
    default: return "Map<String, Object?>";
  }
}

function schemaBundle(types) {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://fiducia.cloud/schemas/generated.bundle.schema.json",
    $defs: Object.fromEntries(types.map((type) => [type.name, type.schema])),
  };
}

// --- emitters: type[] -> { relpath: content } --------------------------------

// Shared Rust body renderer for both the plain `rust` crate and the wasm crate.
// `wasm` adds a `#[derive(Tsify)]` and a real wasm-bindgen ABI so downstream
// functions can accept and return these types directly. `hashmap_as_object`
// keeps the runtime serde-wasm-bindgen representation aligned with the
// generated `Record<..>` declarations instead of emitting JavaScript `Map`s.
// The type bodies are otherwise identical, so the crates never drift.
function renderRustBody(types, { wasm }) {
  const structDerive = wasm
    ? "#[derive(Debug, Clone, Serialize, Deserialize, Tsify)]"
    : "#[derive(Debug, Clone, Serialize, Deserialize)]";
  const enumDerive = wasm
    ? "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Tsify)]"
    : "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]";
  // Compatibility exports carry real #[deprecated] metadata. Derive macros
  // necessarily reference the item they implement, so silence only this
  // generated crate's internal uses; downstream uses still warn normally.
  const header = [`// ${BANNER}`, "", "#![allow(deprecated)]", "", "use serde::{Deserialize, Serialize};"];
  if (wasm) header.push("use tsify::Tsify;", "use wasm_bindgen::prelude::*;");
  const out = [...header, ""];
  // Enums first.
  for (const [enumName, values] of collectEnums(types)) {
    out.push(enumDerive);
    if (wasm) out.push("#[tsify(into_wasm_abi, from_wasm_abi, hashmap_as_object)]");
    out.push(`pub enum ${enumName} {`);
    for (const v of values) out.push(`    #[serde(rename = "${v}")]`, `    ${pascal(v)},`);
    out.push("}", "");
  }
  for (const t of types) {
    if (t.description) out.push(`/// ${cLine(t.description)}`);
    // Derive macros inspect every field/type and would otherwise warn while
    // generating implementations for intentionally retained compatibility
    // members. The deprecation still warns at downstream use sites.
    if (t.deprecated || t.props.some((p) => p.deprecated)) out.push("#[allow(deprecated)]");
    if (t.deprecated) {
      out.push("#[deprecated(", `    note = "${cLine(t.description).replace(/"/g, '\\"')}"`, ")]");
    }
    out.push(structDerive);
    if (wasm) out.push("#[tsify(into_wasm_abi, from_wasm_abi, hashmap_as_object)]");
    out.push(`pub struct ${t.name} {`);
    for (const p of t.props) {
      if (p.description) out.push(`    /// ${cLine(p.description)}`);
      const baseTy = isStringEnum(p.schema) ? enumTypeName(t.name, p.name) : rustType(p.schema);
      const ty = isNullable(p.schema) ? `Option<${baseTy}>` : baseTy;
      const kw = RUST_KEYWORDS.has(p.name);
      const ident = kw ? `r#${p.name}` : p.name;
      if (kw) out.push(`    #[serde(rename = "${p.name}")]`);
      // tsify's default TS for `serde_json::Value` is a bare (undefined) `Value`,
      // and for maps it emits `Map<..>` (wrong for JSON). Pin those fields to the
      // exact type the `typescript` emitter uses so the two TS surfaces agree.
      // Emitted adjacent to the field so it survives the optional serde attrs.
      const tsifyOverride = wasm && /serde_json::Value|BTreeMap/.test(ty)
        ? `    #[tsify(type = "${tsFieldType(p).replace(/"/g, '\\"')}")]`
        : null;
      if (p.required) {
        if (tsifyOverride) out.push(tsifyOverride);
        out.push(`    pub ${ident}: ${ty},`);
      } else {
        out.push(`    #[serde(default, skip_serializing_if = "Option::is_none")]`);
        if (tsifyOverride) out.push(tsifyOverride);
        // Missing and explicit null intentionally collapse to None for an
        // optional nullable JSON field; never emit Option<Option<T>>.
        out.push(`    pub ${ident}: ${isNullable(p.schema) ? ty : `Option<${ty}>`},`);
      }
    }
    out.push("}", "");
  }
  return out.join("\n");
}

function emitRust(types) {
  const cargo = `[package]
name = "fiducia-interfaces"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for fiducia.cloud (see fiducia-interfaces)."

[dependencies]
jsonschema = { version = "0.49.2", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
  const body = `${renderRustBody(types, { wasm: false })}\npub mod validation;\n`;
  const bundle = JSON.stringify(schemaBundle(types));
  const validation = [
    `// ${BANNER}`,
    "",
    "use serde::{de::DeserializeOwned, Serialize};",
    "use serde_json::Value;",
    "use std::{error::Error, fmt};",
    "",
    `const SCHEMA_BUNDLE: &str = ${JSON.stringify(bundle)};`,
    "",
    "#[derive(Debug, Clone, PartialEq, Eq)]",
    "pub struct SchemaValidationError {",
    "    pub schema: String,",
    "    pub message: String,",
    "}",
    "",
    "impl fmt::Display for SchemaValidationError {",
    "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
    '        write!(formatter, "{}: {}", self.schema, self.message)',
    "    }",
    "}",
    "",
    "impl Error for SchemaValidationError {}",
    "",
    "pub fn validate_json(schema_name: &str, value: &Value) -> Result<(), SchemaValidationError> {",
    "    let mut schema: Value =",
    "        serde_json::from_str(SCHEMA_BUNDLE).map_err(|error| SchemaValidationError {",
    "            schema: schema_name.to_owned(),",
    '            message: format!("generated schema bundle is invalid: {error}"),',
    "        })?;",
    '    schema["$ref"] = Value::String(format!("#/$defs/{schema_name}"));',
    "    jsonschema::draft202012::validate(&schema, value).map_err(|error| SchemaValidationError {",
    "        schema: schema_name.to_owned(),",
    "        message: error.to_string(),",
    "    })",
    "}",
    "",
    "pub fn decode_json<T: DeserializeOwned>(",
    "    schema_name: &str,",
    "    value: Value,",
    ") -> Result<T, SchemaValidationError> {",
    "    validate_json(schema_name, &value)?;",
    "    serde_json::from_value(value).map_err(|error| SchemaValidationError {",
    "        schema: schema_name.to_owned(),",
    '        message: format!("typed decode failed after schema validation: {error}"),',
    "    })",
    "}",
    "",
    "pub trait ValidatedJson: Sized + Serialize + DeserializeOwned {",
    "    const SCHEMA_NAME: &'static str;",
    "",
    "    fn from_json(value: Value) -> Result<Self, SchemaValidationError> {",
    "        decode_json(Self::SCHEMA_NAME, value)",
    "    }",
    "",
    "    fn validate(&self) -> Result<(), SchemaValidationError> {",
    "        let value = serde_json::to_value(self).map_err(|error| SchemaValidationError {",
    "            schema: Self::SCHEMA_NAME.to_owned(),",
    '            message: format!("typed encode failed before validation: {error}"),',
    "        })?;",
    "        validate_json(Self::SCHEMA_NAME, &value)",
    "    }",
    "}",
    "",
    ...types.flatMap((type) => [
      `impl ValidatedJson for crate::${type.name} {`,
      `    const SCHEMA_NAME: &'static str = "${type.name}";`,
      "}",
      "",
    ]),
  ].join("\n");
  return {
    "rust/src/lib.rs": body,
    "rust/src/validation.rs": validation,
    "rust/Cargo.toml": cargo,
    "rust/tests/schema_validation.rs": [
      `// ${BANNER}`,
      "",
      "use fiducia_interfaces::{",
      "    validation::ValidatedJson, SyncWritePolicy, SyncWritePolicyFailureMode,",
      "    SyncWritePolicyStrategy, SyncWritePolicyTelemetry,",
      "};",
      "use serde_json::json;",
      "",
      "#[test]",
      "fn typed_values_and_untrusted_json_share_the_canonical_schema() {",
      "    let policy = SyncWritePolicy {",
      "        strategy: SyncWritePolicyStrategy::Optimistic,",
      "        failure_mode: SyncWritePolicyFailureMode::ThrowError,",
      "        telemetry: SyncWritePolicyTelemetry::Lifecycle,",
      "    };",
      "    policy.validate().expect(\"typed policy validates\");",
      "",
      "    let decoded = SyncWritePolicy::from_json(json!({",
      '        "strategy": "pessimistic",',
      '        "failure_mode": "return_result",',
      '        "telemetry": "errors"',
      "    }))",
      '    .expect("wire policy validates and decodes");',
      "    assert_eq!(decoded.strategy, SyncWritePolicyStrategy::Pessimistic);",
      "",
      "    assert!(SyncWritePolicy::from_json(json!({",
      '        "strategy": "sometimes_optimistic",',
      '        "failure_mode": "return_result",',
      '        "telemetry": "errors"',
      "    }))",
      "    .is_err());",
      "}",
      "",
    ].join("\n"),
  };
}

// Wasm build of the Rust types: same serde structs, plus tsify + wasm-bindgen so
// the payloads cross the JS/wasm boundary as real objects and a .d.ts is emitted.
// Kept in a separate crate (generated/rust-wasm) so the plain `rust` crate stays
// dependency-free. Build with: wasm-pack build generated/rust-wasm --target web -- --locked
function emitRustWasm(types) {
  const cargo = `[package]
name = "fiducia-interfaces-wasm"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for fiducia.cloud, compiled to WebAssembly (see fiducia-interfaces)."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
tsify = { version = "0.5", features = ["js"] }
`;
  return { "rust-wasm/src/lib.rs": renderRustBody(types, { wasm: true }), "rust-wasm/Cargo.toml": cargo };
}

// The canonical TypeScript type for a field — shared by the `typescript` emitter
// and the `rust-wasm` tsify overrides so both TS surfaces stay identical.
function tsFieldType(p) {
  const base = isStringEnum(p.schema) ? p.schema.enum.map((v) => `"${v}"`).join(" | ") : tsType(p.schema);
  return isNullable(p.schema) ? `${base} | null` : base;
}

function emitTs(types) {
  const out = [`// ${BANNER}`, ""];
  for (const t of types) {
    if (t.deprecated) out.push(`/** @deprecated ${cBlock(t.description)} */`);
    else if (t.description) out.push(`/** ${cBlock(t.description)} */`);
    out.push(`export type ${t.name} = {`);
    for (const p of t.props) {
      if (p.deprecated) out.push(`  /** @deprecated ${cBlock(p.description)} */`);
      else if (p.description) out.push(`  /** ${cBlock(p.description)} */`);
      const ty = tsFieldType(p);
      out.push(`  ${p.name}${p.required ? "" : "?"}: ${ty};`);
    }
    out.push("};", "");
  }
  const bundle = JSON.stringify(schemaBundle(types), null, 2);
  const zod = [
    `// ${BANNER}`,
    "",
    'import Ajv2020, { type ErrorObject } from "ajv/dist/2020.js";',
    'import addFormats from "ajv-formats";',
    'import { z } from "zod";',
    'import type * as types from "./index.js";',
    "",
    `const schemaBundle = ${bundle} as const;`,
    "const ajv = new Ajv2020({",
    "  allErrors: true,",
    "  strict: true,",
    "  // Draft 2020-12 permits required in a subschema to reference properties",
    "  // declared by its enclosing object; several canonical oneOf/anyOf rules do.",
    "  strictRequired: false,",
    "});",
    "addFormats(ajv);",
    "ajv.addSchema(schemaBundle, schemaBundle.$id);",
    "",
    "function formatIssue(error: ErrorObject): string {",
    '  const path = error.instancePath || "/";',
    '  return `${path} ${error.message ?? "does not match the canonical schema"}`;',
    "}",
    "",
    "function schemaFor<T>(name: string): z.ZodType<T> {",
    "  const validate = ajv.compile({",
    "    $schema: schemaBundle.$schema,",
    "    $ref: `${schemaBundle.$id}#/$defs/${name}`,",
    "  });",
    "  return z.unknown().superRefine((value, context) => {",
    "    if (validate(value)) return;",
    "    for (const error of validate.errors ?? []) {",
    "      context.addIssue({",
    '        code: "custom",',
    "        message: formatIssue(error),",
    "        path: error.instancePath",
    '          .split("/")',
    "          .slice(1)",
    "          .map((part) => part.replaceAll(\"~1\", \"/\").replaceAll(\"~0\", \"~\")),",
    "      });",
    "    }",
    "  }) as z.ZodType<T>;",
    "}",
    "",
    ...types.flatMap((type) => [
      `export const ${type.name}Schema = schemaFor<types.${type.name}>("${type.name}");`,
      "",
    ]),
  ].join("\n");
  return {
    "typescript/index.ts": out.join("\n"),
    "typescript/zod.ts": zod,
  };
}

function emitPython(types) {
  const usesLiteral = types.some((t) => t.props.some((p) => isStringEnum(p.schema)));
  const usesDict = types.some((t) => t.props.some((p) => mapValueSchema(p.schema)));
  const typing = `from typing import List, Optional${usesDict ? ", Dict" : ""}${usesLiteral ? ", Literal" : ""}`;
  const out = [
    `# ${BANNER}`,
    "from __future__ import annotations",
    "from dataclasses import MISSING, dataclass, field as dataclass_field, fields, is_dataclass",
    typing,
    "",
    "def to_wire(value):",
    '    """Convert generated dataclasses to canonical snake-case JSON values."""',
    "    if is_dataclass(value):",
    "        output = {}",
    "        for info in fields(value):",
    "            item = getattr(value, info.name)",
    "            if item is None and info.default is not MISSING:",
    "                continue",
    '            output[info.metadata.get("wire_name", info.name)] = to_wire(item)',
    "        return output",
    "    if isinstance(value, list):",
    "        return [to_wire(item) for item in value]",
    "    if isinstance(value, tuple):",
    "        return [to_wire(item) for item in value]",
    "    if isinstance(value, dict):",
    "        return {key: to_wire(item) for key, item in value.items()}",
    "    return value",
    "",
  ];
  for (const t of types) {
    out.push("@dataclass", `class ${t.name}:`);
    if (t.description) out.push(`    """${pyDoc(t.description)}"""`);
    const ordered = [...t.props].sort((a, b) => Number(b.required) - Number(a.required));
    if (ordered.length === 0) out.push("    pass");
    for (const p of ordered) {
      const raw = isStringEnum(p.schema) ? `Literal[${p.schema.enum.map((v) => `"${v}"`).join(", ")}]` : pyType(p.schema);
      const base = isNullable(p.schema) ? `Optional[${raw}]` : raw;
      const ident = PYTHON_KEYWORDS.has(p.name) ? `${p.name}_` : p.name;
      if (ident !== p.name) out.push(`    # JSON field: ${p.name}`);
      if (ident !== p.name) {
        const field = p.required
          ? `dataclass_field(metadata={"wire_name": "${p.name}"})`
          : `dataclass_field(default=None, metadata={"wire_name": "${p.name}"})`;
        out.push(`    ${ident}: ${p.required ? base : (isNullable(p.schema) ? base : `Optional[${base}]`)} = ${field}`);
      } else {
        out.push(p.required ? `    ${ident}: ${base}` : `    ${ident}: ${isNullable(p.schema) ? base : `Optional[${base}]`} = None`);
      }
    }
    out.push("");
  }
  return { "python/fiducia_interfaces.py": out.join("\n") };
}

function emitGo(types) {
  const out = [`// ${BANNER}`, "", "package fiducia", ""];
  for (const t of types) {
    if (t.deprecated) out.push(`// ${t.name}: Deprecated: ${cLine(t.description)}`);
    else if (t.description) out.push(`// ${t.name}: ${cLine(t.description)}`);
    out.push(`type ${t.name} struct {`);
    for (const p of t.props) {
      let doc = p.description ? cLine(p.description) : "";
      if (p.deprecated) doc = `Deprecated: ${doc}`;
      if (isStringEnum(p.schema)) doc = `${doc} (one of: ${p.schema.enum.join(", ")})`.trim();
      if (doc) out.push(`\t// ${doc}`);
      const ty = goType(p.schema); // enums are plain strings in Go
      const tag = p.required ? `json:"${p.name}"` : `json:"${p.name},omitempty"`;
      out.push(`\t${pascal(p.name)} ${p.required && !isNullable(p.schema) ? "" : "*"}${ty} \`${tag}\``);
    }
    out.push("}", "");
  }
  return { "go/interfaces.go": out.join("\n") };
}

function dartFieldType(typeName, property) {
  const raw = isStringEnum(property.schema)
    ? enumTypeName(typeName, property.name)
    : dartType(property.schema);
  return property.required && !isNullable(property.schema) ? raw : `${raw}?`;
}

function dartDecode(schema, expression, at, enumName = null) {
  const nullable = isNullable(schema);
  const inner = nonNullSchema(schema);
  const ref = refName(inner);
  let decoded;
  if (enumName) {
    decoded = `${enumName}.fromWire(_string(${expression}, ${JSON.stringify(at)}))`;
  } else if (ref) {
    decoded = `${ref}.fromJson(_map(${expression}, ${JSON.stringify(at)}))`;
  } else {
    const mapValue = mapValueSchema(inner);
    if (mapValue) {
      decoded =
        `Map<String, ${dartType(mapValue)}>.fromEntries(` +
        `_map(${expression}, ${JSON.stringify(at)}).entries.map((entry) => ` +
        `MapEntry(entry.key, ${dartDecode(mapValue, "entry.value", `${at} value`)})))`;
    } else {
      switch (inner.type) {
        case "string": decoded = `_string(${expression}, ${JSON.stringify(at)})`; break;
        case "integer": decoded = `_integer(${expression}, ${JSON.stringify(at)})`; break;
        case "number": decoded = `_number(${expression}, ${JSON.stringify(at)})`; break;
        case "boolean": decoded = `_boolean(${expression}, ${JSON.stringify(at)})`; break;
        case "array":
          decoded =
            `_list(${expression}, ${JSON.stringify(at)}).map((value) => ` +
            `${dartDecode(inner.items || {}, "value", `${at} item`)}).toList(growable: false)`;
          break;
        default: decoded = `_map(${expression}, ${JSON.stringify(at)})`;
      }
    }
  }
  return nullable ? `${expression} == null ? null : ${decoded}` : decoded;
}

function dartEncode(schema, expression, enumName = null, optional = false) {
  const inner = nonNullSchema(schema);
  const ref = refName(inner);
  const nullAware = optional || isNullable(schema) ? "?" : "";
  let encoded;
  if (enumName) {
    encoded = `${expression}${nullAware}.wireValue`;
  } else if (ref) {
    encoded = `${expression}${nullAware}.toJson()`;
  } else {
    const mapValue = mapValueSchema(inner);
    if (mapValue) {
      encoded =
        `${expression}${nullAware}.map((key, value) => MapEntry(key, ` +
        `${dartEncode(mapValue, "value")}))`;
    } else if (inner.type === "array") {
      encoded =
        `${expression}${nullAware}.map((value) => ${dartEncode(inner.items || {}, "value")}).toList(growable: false)`;
    } else {
      encoded = expression;
    }
  }
  return encoded;
}

function emitDart(types) {
  const encodedBundle = Buffer.from(JSON.stringify(schemaBundle(types)), "utf8").toString("base64");
  const out = [
    `// ${BANNER}`,
    "",
    "import 'dart:convert';",
    "",
    `const _schemaBundleBase64 = '${encodedBundle}';`,
    "late final Map<String, Object?> _schemaBundle = Map<String, Object?>.from(",
    "  jsonDecode(utf8.decode(base64Decode(_schemaBundleBase64))) as Map,",
    ");",
    "",
    "Map<String, Object?> _schemaMap(Object? value, String at) {",
    "  if (value is! Map) throw FormatException('$at must be an object');",
    "  return Map<String, Object?>.from(value);",
    "}",
    "",
    "Map<String, Object?> _map(Object? value, String at) => _schemaMap(value, at);",
    "List<Object?> _list(Object? value, String at) {",
    "  if (value is! List) throw FormatException('$at must be an array');",
    "  return List<Object?>.from(value);",
    "}",
    "String _string(Object? value, String at) {",
    "  if (value is! String) throw FormatException('$at must be a string');",
    "  return value;",
    "}",
    "int _integer(Object? value, String at) {",
    "  if (value is! int) throw FormatException('$at must be an integer');",
    "  return value;",
    "}",
    "num _number(Object? value, String at) {",
    "  if (value is! num || !value.isFinite) throw FormatException('$at must be a finite number');",
    "  return value;",
    "}",
    "bool _boolean(Object? value, String at) {",
    "  if (value is! bool) throw FormatException('$at must be a boolean');",
    "  return value;",
    "}",
    "",
    "bool _deepEquals(Object? left, Object? right) {",
    "  if (left is List && right is List) {",
    "    if (left.length != right.length) return false;",
    "    for (var index = 0; index < left.length; index += 1) {",
    "      if (!_deepEquals(left[index], right[index])) return false;",
    "    }",
    "    return true;",
    "  }",
    "  if (left is Map && right is Map) {",
    "    if (left.length != right.length) return false;",
    "    for (final entry in left.entries) {",
    "      if (!right.containsKey(entry.key) || !_deepEquals(entry.value, right[entry.key])) return false;",
    "    }",
    "    return true;",
    "  }",
    "  return left == right;",
    "}",
    "",
    "bool _matches(Map<String, Object?> schema, Object? value, String at) {",
    "  try {",
    "    _validateSchema(schema, value, at);",
    "    return true;",
    "  } on FormatException {",
    "    return false;",
    "  }",
    "}",
    "",
    "void _validateSchema(Map<String, Object?> schema, Object? value, String at) {",
    "  final reference = schema[r'$ref'];",
    "  if (reference is String) {",
    "    final name = reference.split('/').last;",
    "    final definitions = _schemaMap(_schemaBundle[r'$defs'], r'$defs');",
    "    _validateSchema(_schemaMap(definitions[name], name), value, at);",
    "    return;",
    "  }",
    "",
    "  final rawType = schema['type'];",
    "  if (rawType is List && rawType.contains('null')) {",
    "    if (value == null) return;",
    "    final nonNull = rawType.where((candidate) => candidate != 'null').toList();",
    "    if (nonNull.length != 1) throw FormatException('$at has an unsupported nullable schema');",
    "    schema = <String, Object?>{...schema, 'type': nonNull.single};",
    "  }",
    "  if (schema.containsKey('const') && !_deepEquals(value, schema['const'])) {",
    "    throw FormatException('$at does not equal the required constant');",
    "  }",
    "",
    "  final required = schema['required'];",
    "  if (required is List) {",
    "    final object = _schemaMap(value, at);",
    "    for (final name in required) {",
    "      if (!object.containsKey(name)) throw FormatException('$at.$name is required');",
    "    }",
    "  }",
    "",
    "  final anyOf = schema['anyOf'];",
    "  if (anyOf is List && !anyOf.any((candidate) => _matches(_schemaMap(candidate, '$at anyOf'), value, at))) {",
    "    throw FormatException('$at does not match any allowed schema');",
    "  }",
    "  final oneOf = schema['oneOf'];",
    "  if (oneOf is List) {",
    "    final matches = oneOf.where((candidate) => _matches(_schemaMap(candidate, '$at oneOf'), value, at)).length;",
    "    if (matches != 1) throw FormatException('$at must match exactly one allowed schema');",
    "  }",
    "  final allOf = schema['allOf'];",
    "  if (allOf is List) {",
    "    for (final candidate in allOf) {",
    "      _validateSchema(_schemaMap(candidate, '$at allOf'), value, at);",
    "    }",
    "  }",
    "  final condition = schema['if'];",
    "  if (condition is Map) {",
    "    final branch = _matches(_schemaMap(condition, '$at if'), value, at) ? schema['then'] : schema['else'];",
    "    if (branch is Map) _validateSchema(_schemaMap(branch, '$at branch'), value, at);",
    "  }",
    "  final forbidden = schema['not'];",
    "  if (forbidden is Map && _matches(_schemaMap(forbidden, '$at not'), value, at)) {",
    "    throw FormatException('$at matches a forbidden schema');",
    "  }",
    "",
    "  final properties = schema['properties'];",
    "  if (rawType != 'object' && properties is Map && value is Map) {",
    "    for (final entry in properties.entries) {",
    "      if (value.containsKey(entry.key)) {",
    "        _validateSchema(_schemaMap(entry.value, '$at.${entry.key}'), value[entry.key], '$at.${entry.key}');",
    "      }",
    "    }",
    "  }",
    "",
    "  switch (schema['type']) {",
    "    case 'object':",
    "      final object = _schemaMap(value, at);",
    "      final declared = properties is Map ? properties : const <String, Object?>{};",
    "      for (final entry in object.entries) {",
    "        if (declared.containsKey(entry.key)) {",
    "          _validateSchema(_schemaMap(declared[entry.key], '$at.${entry.key}'), entry.value, '$at.${entry.key}');",
    "        } else if (schema['additionalProperties'] == false) {",
    "          throw FormatException('$at.${entry.key} is not allowed');",
    "        } else if (schema['additionalProperties'] is Map) {",
    "          _validateSchema(_schemaMap(schema['additionalProperties'], '$at additionalProperties'), entry.value, '$at.${entry.key}');",
    "        }",
    "      }",
    "      break;",
    "    case 'array':",
    "      final values = _list(value, at);",
    "      final minItems = schema['minItems'];",
    "      final maxItems = schema['maxItems'];",
    "      if (minItems is int && values.length < minItems) throw FormatException('$at has too few items');",
    "      if (maxItems is int && values.length > maxItems) throw FormatException('$at has too many items');",
    "      if (schema['uniqueItems'] == true) {",
    "        for (var left = 0; left < values.length; left += 1) {",
    "          for (var right = left + 1; right < values.length; right += 1) {",
    "            if (_deepEquals(values[left], values[right])) throw FormatException('$at items must be unique');",
    "          }",
    "        }",
    "      }",
    "      final itemSchema = schema['items'];",
    "      if (itemSchema is Map) {",
    "        for (var index = 0; index < values.length; index += 1) {",
    "          _validateSchema(_schemaMap(itemSchema, '$at items'), values[index], '$at[$index]');",
    "        }",
    "      }",
    "      break;",
    "    case 'string':",
    "      final text = _string(value, at);",
    "      final length = text.runes.length;",
    "      final minLength = schema['minLength'];",
    "      final maxLength = schema['maxLength'];",
    "      if (minLength is int && length < minLength) throw FormatException('$at is too short');",
    "      if (maxLength is int && length > maxLength) throw FormatException('$at is too long');",
    "      final pattern = schema['pattern'];",
    "      if (pattern is String && !RegExp(pattern).hasMatch(text)) throw FormatException('$at has an invalid format');",
    "      break;",
    "    case 'integer':",
    "      _integer(value, at);",
    "      break;",
    "    case 'number':",
    "      _number(value, at);",
    "      break;",
    "    case 'boolean':",
    "      _boolean(value, at);",
    "      break;",
    "  }",
    "",
    "  if (value is num) {",
    "    final minimum = schema['minimum'];",
    "    final maximum = schema['maximum'];",
    "    if (minimum is num && value < minimum) throw FormatException('$at is below its minimum');",
    "    if (maximum is num && value > maximum) throw FormatException('$at is above its maximum');",
    "  }",
    "  final allowed = schema['enum'];",
    "  if (allowed is List && !allowed.any((candidate) => _deepEquals(candidate, value))) {",
    "    throw FormatException('$at is not an allowed value');",
    "  }",
    "}",
    "",
    "void validateFiduciaJson(String schemaName, Object? value) {",
    "  final definitions = _schemaMap(_schemaBundle[r'$defs'], r'$defs');",
    "  final schema = definitions[schemaName];",
    "  if (schema == null) throw ArgumentError.value(schemaName, 'schemaName', 'unknown Fiducia schema');",
    "  _validateSchema(_schemaMap(schema, schemaName), value, schemaName);",
    "}",
    "",
  ];

  for (const [enumName, values] of collectEnums(types)) {
    out.push(`enum ${enumName} {`);
    values.forEach((value, index) => {
      out.push(`  ${value}${index === values.length - 1 ? ";" : ","}`);
    });
    out.push(
      "",
      "  String get wireValue => name;",
      "",
      `  static ${enumName} fromWire(Object? value) {`,
      "    return switch (value) {",
      ...values.map((value) => `      '${value}' => ${enumName}.${value},`),
      `      _ => throw FormatException('unsupported ${enumName} value: $value'),`,
      "    };",
      "  }",
      "}",
      "",
    );
  }

  for (const type of types) {
    out.push(`final class ${type.name} {`);
    const ordered = [...type.props].sort((left, right) => Number(right.required) - Number(left.required));
    if (ordered.length === 0) {
      out.push(`  const ${type.name}();`, "");
    } else {
      out.push(`  const ${type.name}({`);
      for (const property of ordered) {
        out.push(`    ${property.required ? "required " : ""}this.${property.name},`);
      }
      out.push("  });", "");
    }
    for (const property of type.props) {
      out.push(`  final ${dartFieldType(type.name, property)} ${property.name};`);
    }
    if (type.props.length > 0) out.push("");
    out.push(
      `  factory ${type.name}.fromJson(Map<String, Object?> json) {`,
      `    validateFiduciaJson('${type.name}', json);`,
      `    return ${type.name}(`,
    );
    for (const property of type.props) {
      const expression = `json['${property.name}']`;
      const enumName = isStringEnum(property.schema)
        ? enumTypeName(type.name, property.name)
        : null;
      const decoded = dartDecode(property.schema, expression, `${type.name}.${property.name}`, enumName);
      out.push(
        `      ${property.name}: ${property.required && !isNullable(property.schema) ? decoded : `${expression} == null ? null : ${decoded}`},`,
      );
    }
    out.push("    );", "  }", "", "  Map<String, Object?> toJson() => {");
    for (const property of type.props) {
      const enumName = isStringEnum(property.schema)
        ? enumTypeName(type.name, property.name)
        : null;
      const expression = property.name;
      const encoded = dartEncode(
        property.schema,
        expression,
        enumName,
        !property.required,
      );
      if (property.required) {
        out.push(`    '${property.name}': ${encoded},`);
      } else {
        out.push(`    if (${property.name} != null) '${property.name}': ${encoded},`);
      }
    }
    out.push("  };", "}", "");
  }

  const pubspec = [
    "name: fiducia_interfaces",
    "description: Generated, JSON-Schema-validated wire types for fiducia.cloud.",
    "version: 0.1.0",
    "repository: https://github.com/fiducia-cloud/fiducia-interfaces",
    "",
    "environment:",
    '  sdk: ">=3.9.0 <4.0.0"',
    "",
    "dev_dependencies:",
    "  test: ^1.26.3",
    "",
  ].join("\n");
  const test = [
    `// ${BANNER}`,
    "",
    "import 'package:fiducia_interfaces/fiducia_interfaces.dart';",
    "import 'package:test/test.dart';",
    "",
    "void main() {",
    "  test('typed and untrusted sync policies share canonical validation', () {",
    "    final policy = SyncWritePolicy.fromJson(const {",
    "      'strategy': 'optimistic',",
    "      'failure_mode': 'throw_error',",
    "      'telemetry': 'lifecycle',",
    "    });",
    "    expect(policy.strategy, SyncWritePolicyStrategy.optimistic);",
    "    expect(policy.toJson()['failure_mode'], 'throw_error');",
    "",
    "    expect(",
    "      () => SyncWritePolicy.fromJson(const {",
    "        'strategy': 'sometimes_optimistic',",
    "        'failure_mode': 'return_result',",
    "        'telemetry': 'errors',",
    "      }),",
    "      throwsFormatException,",
    "    );",
    "  });",
    "}",
    "",
  ].join("\n");
  const readme = [
    "# fiducia_interfaces",
    "",
    "Generated Dart types and runtime validators for the canonical Draft 2020-12",
    "schemas in `fiducia-interfaces/schema`. Edit the JSON Schema and regenerate;",
    "never hand-edit `lib/fiducia_interfaces.dart`.",
    "",
  ].join("\n");
  return {
    "dart/lib/fiducia_interfaces.dart": out.join("\n"),
    "dart/pubspec.yaml": pubspec,
    "dart/test/schema_validation_test.dart": test,
    "dart/README.md": readme,
  };
}

const EMITTERS = {
  rust: emitRust,
  "rust-wasm": emitRustWasm,
  typescript: emitTs,
  python: emitPython,
  go: emitGo,
  dart: emitDart,
  // Future client emitters can add ruby, java, csharp, php, or elixir here.
};

// --- run ---------------------------------------------------------------------

export function build() {
  const types = loadTypes();
  const files = {};
  for (const emit of Object.values(EMITTERS)) Object.assign(files, emit(types));
  return files;
}
export { loadTypes, pascal, oneLine, refName, isStringEnum, enumTypeName, collectEnums };

function main() {
  const check = process.argv.includes("--check") || /^(1|true|yes|on)$/i.test(process.env.FIDUCIA_GENERATE_CHECK ?? "");
  const only = process.argv.find((arg) => arg.startsWith("--only="))?.slice("--only=".length);
  let files;
  try { files = build(); }
  catch (e) {
    if (e instanceof GenError) { console.error(`error: ${e.message}`); process.exit(2); }
    throw e;
  }
  if (only && !Object.hasOwn(files, only)) {
    console.error(`error: unknown generated file for --only: ${only}`);
    process.exit(2);
  }
  const selectedFiles = only ? { [only]: files[only] } : files;
  let drift = 0;
  for (const [rel, content] of Object.entries(selectedFiles)) {
    const abs = path.join(genDir, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) { console.error(`drift: ${rel}`); drift++; }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) { console.error(`${drift} file(s) out of date — run: node src/generate.mjs`); process.exit(1); }
  if (check) console.log("generated files up to date");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
