#!/usr/bin/env node
// SQL DDL -> DB row types for fiducia.cloud, per plane.
//
//   node src/generate-db.mjs          # write generated/rust-db + generated/typescript/db
//   node src/generate-db.mjs --check  # CI: fail if generated files are stale
//
// sql/<plane>.sql is the source of truth. Emits:
//   - Rust  sqlx::FromRow structs (generated/rust-db/, feature-light standalone crate)
//   - TS    row types             (generated/typescript/db/<plane>.ts)
// consumed by the backends (SQLx) and the IndexedDB sync stores respectively, so
// Postgres -> SQLx -> WS -> IndexedDB share one generated shape per plane.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const sqlDir = path.join(root, "sql");
const genDir = path.join(root, "generated");
const BANNER =
  "AUTOGENERATED by src/generate-db.mjs — do not edit by hand; edit sql/<plane>.sql and regenerate.";

const PLANES = [
  { name: "customer", file: "customer.sql" },
  { name: "admin", file: "admin.sql" },
  { name: "ai_agent_control_plane", file: "ai_agent_control_plane.sql" },
  { name: "operations_control_plane", file: "operations_control_plane.sql" },
  { name: "ai_agent_bridge", file: "ai_agent_bridge.sql" },
];

const RUST_KEYWORDS = new Set([
  "as","break","const","continue","crate","dyn","else","enum","extern","false","fn","for","if","impl",
  "in","let","loop","match","mod","move","mut","pub","ref","return","self","static","struct","super",
  "trait","true","type","unsafe","use","where","while","async","await","box","union",
]);
const pascal = (s) => s.split(/[_\-\s]+/).map((w) => (w ? w[0].toUpperCase() + w.slice(1) : "")).join("");
const structName = (table) => `${pascal(table)}Row`;

// --- parse ---------------------------------------------------------------------

// Lines inside a CREATE TABLE body that are table constraints / comments, not columns.
const NON_COLUMN = /^(constraint|primary\s+key|unique|foreign\s+key|check|--|\))/i;

function parseColumns(body) {
  const columns = [];
  for (let line of body.split("\n")) {
    line = line.trim().replace(/,\s*$/, "");
    if (!line || NON_COLUMN.test(line)) continue;
    const tokens = line.split(/\s+/);
    const name = tokens[0];
    const sqlType = tokens[1] || "";
    // A column is NOT NULL if it says so or is a (single-column) primary key.
    const notNull = /\bnot\s+null\b/i.test(line) || /\bprimary\s+key\b/i.test(line);
    columns.push({ name, sqlType, nullable: !notNull });
  }
  return columns;
}

function parseTables(sql) {
  const tables = [];
  const re = /create table if not exists\s+(\w+)\s*\(([\s\S]*?)\n\)\s*;/gi;
  let m;
  while ((m = re.exec(sql))) {
    tables.push({ name: m[1], columns: parseColumns(m[2]) });
  }
  return tables;
}

// --- type mapping --------------------------------------------------------------

function baseType(sqlType) {
  const t = sqlType.toLowerCase();
  if (t.startsWith("uuid")) return "uuid";
  if (t.startsWith("varchar") || t.startsWith("char") || t.startsWith("text")) return "string";
  if (t.startsWith("timestamptz") || t.startsWith("timestamp")) return "timestamp";
  if (t.startsWith("boolean") || t.startsWith("bool")) return "bool";
  if (t.startsWith("bigint") || t.startsWith("int8")) return "i64";
  if (t.startsWith("integer") || t.startsWith("int4") || t === "int") return "i32";
  if (t.startsWith("smallint") || t.startsWith("int2")) return "i16";
  if (t.startsWith("jsonb") || t.startsWith("json")) return "json";
  if (t.startsWith("inet")) return "inet";
  if (t.startsWith("vector")) return "vector";
  return "json"; // unknown -> opaque JSON value
}

// inet -> String: sqlx has no native String decode for inet, so queries selecting
// an inet column should cast it (`source_ip::text`). Noted; only audit source_ip.
const RUST = {
  uuid: "uuid::Uuid",
  string: "String",
  timestamp: "chrono::DateTime<chrono::Utc>",
  bool: "bool",
  i64: "i64",
  i32: "i32",
  i16: "i16",
  json: "serde_json::Value",
  inet: "String",
  vector: "pgvector::Vector",
};
const TS = {
  uuid: "string",
  string: "string",
  timestamp: "string",
  bool: "boolean",
  i64: "number",
  i32: "number",
  i16: "number",
  json: "unknown",
  inet: "string",
  vector: "number[]",
};

// --- emit ----------------------------------------------------------------------

function emitRustModule(tables) {
  const out = [`// ${BANNER}`, ""];
  for (const t of tables) {
    out.push(
      "#[derive(Debug, Clone, sqlx::FromRow, serde::Serialize, serde::Deserialize)]",
      `pub struct ${structName(t.name)} {`,
    );
    for (const c of t.columns) {
      const base = RUST[baseType(c.sqlType)];
      const ty = c.nullable ? `Option<${base}>` : base;
      const kw = RUST_KEYWORDS.has(c.name);
      if (kw) out.push(`    #[sqlx(rename = "${c.name}")]`);
      out.push(`    pub ${kw ? `r#${c.name}` : c.name}: ${ty},`);
    }
    out.push("}", "");
  }
  return out.join("\n");
}

function emitTsModule(tables) {
  const out = [`// ${BANNER}`, ""];
  for (const t of tables) {
    out.push(`export type ${structName(t.name)} = {`);
    for (const c of t.columns) {
      const base = TS[baseType(c.sqlType)];
      out.push(`  ${c.name}: ${c.nullable ? `${base} | null` : base};`);
    }
    out.push("};", "");
  }
  return out.join("\n");
}

const CARGO = `[package]
name = "fiducia-interfaces-db"
version = "0.1.0"
edition = "2021"
description = "Generated sqlx::FromRow row types for the fiducia.cloud Postgres planes (see fiducia-interfaces)."

[dependencies]
sqlx = { version = "0.8", default-features = false, features = ["postgres", "uuid", "chrono", "json", "macros"] }
uuid = { version = "1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pgvector = { version = "0.4", features = ["sqlx", "serde"] }
`;

export function build() {
  const files = {};
  const mods = [];
  for (const plane of PLANES) {
    const sql = fs.readFileSync(path.join(sqlDir, plane.file), "utf8");
    const tables = parseTables(sql);
    files[`rust-db/src/${plane.name}.rs`] = emitRustModule(tables);
    files[`typescript/db/${plane.name}.ts`] = emitTsModule(tables);
    mods.push(plane.name);
  }
  files["rust-db/src/lib.rs"] =
    `// ${BANNER}\n#![allow(dead_code)]\n\n${mods
      .sort()
      .map((m) => `pub mod ${m};`)
      .join("\n")}\n`;
  files["rust-db/Cargo.toml"] = CARGO;
  return files;
}

export { parseTables, parseColumns, baseType, structName };

function main() {
  const check = process.argv.includes("--check") || /^(1|true|yes|on)$/i.test(process.env.FIDUCIA_GENERATE_CHECK ?? "");
  const files = build();
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(genDir, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) {
        console.error(`drift: ${rel}`);
        drift++;
      }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) {
    console.error(`${drift} db file(s) out of date — run: node src/generate-db.mjs`);
    process.exit(1);
  }
  if (check) console.log("generated db files up to date");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
