#!/usr/bin/env node
// JSON Schema -> per-language types for fiducia.cloud.
//
//   node src/generate.mjs          # write generated/<lang>/...
//   node src/generate.mjs --check  # verify generated files are up to date (CI)
//
// JSON Schema (schema/*.schema.json) is the source of truth. Generated files are
// adapters only — never hand-edit them. Adding a language is one entry in
// EMITTERS; adding a type is one entry in a schema file + schema/index.json.
//
// Hardened: validates the index + every schema, rejects duplicate type names and
// dangling $refs, enforces snake_case field names, sanitizes doc comments,
// raw-escapes Rust keyword fields, and emits typed enums for string `enum`s.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const schemaDir = path.join(root, "schema");
const genDir = path.join(root, "generated");

const BANNER = "AUTOGENERATED by src/generate.mjs — do not edit by hand; edit schema/ and regenerate.";

class GenError extends Error {}
const fail = (msg) => { throw new GenError(msg); };

// --- helpers -----------------------------------------------------------------

const oneLine = (s) => String(s || "").replace(/\s+/g, " ").trim();
const pascal = (s) => s.split(/[_\-\s]+/).map((w) => (w ? w[0].toUpperCase() + w.slice(1) : "")).join("");
// Comment-escapers so a description can never break the generated file.
const cLine = (s) => oneLine(s);                                  // // and /// and #
const cBlock = (s) => oneLine(s).replace(/\*\//g, "*\\/");        // /** ... */
const pyDoc = (s) => oneLine(s).replace(/"""/g, "'''").replace(/\\/g, "\\\\"); // """ ... """

const RUST_KEYWORDS = new Set([
  "as","break","const","continue","crate","dyn","else","enum","extern","false","fn","for","if","impl",
  "in","let","loop","match","mod","move","mut","pub","ref","return","self","static","struct","super",
  "trait","true","type","unsafe","use","where","while","async","await","box","union",
]);
const FIELD_RE = /^[a-z][a-z0-9_]*$/;

const refName = (s) => (s && s.$ref ? s.$ref.split("/").pop() : null);
const isStringEnum = (s) => s && s.type === "string" && Array.isArray(s.enum) && s.enum.length > 0;
const enumTypeName = (typeName, fieldName) => `${typeName}${pascal(fieldName)}`;

// --- load + validate ----------------------------------------------------------

function loadTypes() {
  const indexPath = path.join(schemaDir, "index.json");
  if (!fs.existsSync(indexPath)) fail(`missing ${indexPath}`);
  let index;
  try { index = JSON.parse(fs.readFileSync(indexPath, "utf8")); }
  catch (e) { fail(`schema/index.json is not valid JSON: ${e.message}`); }
  if (!Array.isArray(index.schemas)) fail("schema/index.json must have a `schemas` array");

  const types = [];
  const seen = new Map(); // type name -> source file (duplicate detection)

  for (const file of index.schemas) {
    if (typeof file !== "string" || !file.endsWith(".schema.json")) {
      fail(`schema/index.json entry is not a *.schema.json file: ${JSON.stringify(file)}`);
    }
    const abs = path.join(schemaDir, file);
    if (!fs.existsSync(abs)) fail(`schema/index.json lists ${file} but it does not exist`);
    let doc;
    try { doc = JSON.parse(fs.readFileSync(abs, "utf8")); }
    catch (e) { fail(`${file} is not valid JSON: ${e.message}`); }
    if (!doc.$defs || typeof doc.$defs !== "object") fail(`${file} has no $defs object`);

    for (const [name, def] of Object.entries(doc.$defs)) {
      if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) fail(`${file}: $def name must be PascalCase: ${name}`);
      if (seen.has(name)) fail(`duplicate type name "${name}" in ${file} and ${seen.get(name)}`);
      seen.set(name, file);
      const required = new Set(def.required || []);
      const props = Object.entries(def.properties || {}).map(([pname, pschema]) => {
        if (!FIELD_RE.test(pname)) fail(`${file}:${name}: property "${pname}" must be snake_case (${FIELD_RE})`);
        return { name: pname, schema: pschema, required: required.has(pname), description: pschema.description || "" };
      });
      types.push({ name, description: def.description || "", props, source: file });
    }
  }

  // Validate every $ref points at a known type.
  const known = new Set(types.map((t) => t.name));
  for (const t of types) {
    for (const p of t.props) {
      for (const s of [p.schema, p.schema && p.schema.items]) {
        const r = refName(s);
        if (r && !known.has(r)) fail(`${t.source}:${t.name}.${p.name}: $ref to unknown type "${r}"`);
      }
    }
  }
  return types;
}

// Collect distinct enum types referenced by fields (for languages with enums).
function collectEnums(types) {
  const enums = new Map(); // enumName -> values[]
  for (const t of types) {
    for (const p of t.props) {
      if (isStringEnum(p.schema)) enums.set(enumTypeName(t.name, p.name), p.schema.enum.slice());
    }
  }
  return enums;
}

// --- per-language scalar resolvers (non-enum) --------------------------------

function rustType(s) {
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "String";
    case "integer": return "i64";
    case "number": return "f64";
    case "boolean": return "bool";
    case "array": return `Vec<${rustType(s.items || {})}>`;
    default: return "serde_json::Value";
  }
}
function tsType(s) {
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(s.items || {})}[]`;
    default: return "Record<string, unknown>";
  }
}
function pyType(s) {
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "str";
    case "integer": return "int";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return `List[${pyType(s.items || {})}]`;
    default: return "dict";
  }
}
function goType(s) {
  const r = refName(s); if (r) return r;
  switch (s.type) {
    case "string": return "string";
    case "integer": return "int64";
    case "number": return "float64";
    case "boolean": return "bool";
    case "array": return `[]${goType(s.items || {})}`;
    default: return "map[string]any";
  }
}

// --- emitters: type[] -> { relpath: content } --------------------------------

function emitRust(types) {
  const out = [`// ${BANNER}`, "", "use serde::{Deserialize, Serialize};", ""];
  // Enums first.
  for (const [enumName, values] of collectEnums(types)) {
    out.push("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]", `pub enum ${enumName} {`);
    for (const v of values) out.push(`    #[serde(rename = "${v}")]`, `    ${pascal(v)},`);
    out.push("}", "");
  }
  for (const t of types) {
    if (t.description) out.push(`/// ${cLine(t.description)}`);
    out.push("#[derive(Debug, Clone, Serialize, Deserialize)]", `pub struct ${t.name} {`);
    for (const p of t.props) {
      if (p.description) out.push(`    /// ${cLine(p.description)}`);
      const ty = isStringEnum(p.schema) ? enumTypeName(t.name, p.name) : rustType(p.schema);
      const kw = RUST_KEYWORDS.has(p.name);
      const ident = kw ? `r#${p.name}` : p.name;
      if (kw) out.push(`    #[serde(rename = "${p.name}")]`);
      if (p.required) {
        out.push(`    pub ${ident}: ${ty},`);
      } else {
        out.push(`    #[serde(default, skip_serializing_if = "Option::is_none")]`, `    pub ${ident}: Option<${ty}>,`);
      }
    }
    out.push("}", "");
  }
  const cargo = `[package]
name = "fiducia-interfaces"
version = "0.1.0"
edition = "2021"
description = "Generated typed payloads for fiducia.cloud (see fiducia-interfaces)."

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
  return { "rust/src/lib.rs": out.join("\n"), "rust/Cargo.toml": cargo };
}

function emitTs(types) {
  const out = [`// ${BANNER}`, ""];
  for (const t of types) {
    if (t.description) out.push(`/** ${cBlock(t.description)} */`);
    out.push(`export type ${t.name} = {`);
    for (const p of t.props) {
      if (p.description) out.push(`  /** ${cBlock(p.description)} */`);
      const ty = isStringEnum(p.schema) ? p.schema.enum.map((v) => `"${v}"`).join(" | ") : tsType(p.schema);
      out.push(`  ${p.name}${p.required ? "" : "?"}: ${ty};`);
    }
    out.push("};", "");
  }
  return { "typescript/index.ts": out.join("\n") };
}

function emitPython(types) {
  const usesLiteral = types.some((t) => t.props.some((p) => isStringEnum(p.schema)));
  const typing = `from typing import List, Optional${usesLiteral ? ", Literal" : ""}`;
  const out = [`# ${BANNER}`, "from __future__ import annotations", "from dataclasses import dataclass", typing, ""];
  for (const t of types) {
    out.push("@dataclass", `class ${t.name}:`);
    if (t.description) out.push(`    """${pyDoc(t.description)}"""`);
    const ordered = [...t.props].sort((a, b) => Number(b.required) - Number(a.required));
    if (ordered.length === 0) out.push("    pass");
    for (const p of ordered) {
      const base = isStringEnum(p.schema) ? `Literal[${p.schema.enum.map((v) => `"${v}"`).join(", ")}]` : pyType(p.schema);
      out.push(p.required ? `    ${p.name}: ${base}` : `    ${p.name}: Optional[${base}] = None`);
    }
    out.push("");
  }
  return { "python/fiducia_interfaces.py": out.join("\n") };
}

function emitGo(types) {
  const out = [`// ${BANNER}`, "", "package fiducia", ""];
  for (const t of types) {
    if (t.description) out.push(`// ${t.name}: ${cLine(t.description)}`);
    out.push(`type ${t.name} struct {`);
    for (const p of t.props) {
      let doc = p.description ? cLine(p.description) : "";
      if (isStringEnum(p.schema)) doc = `${doc} (one of: ${p.schema.enum.join(", ")})`.trim();
      if (doc) out.push(`\t// ${doc}`);
      const ty = goType(p.schema); // enums are plain strings in Go
      const tag = p.required ? `json:"${p.name}"` : `json:"${p.name},omitempty"`;
      out.push(`\t${pascal(p.name)} ${p.required ? "" : "*"}${ty} \`${tag}\``);
    }
    out.push("}", "");
  }
  return { "go/interfaces.go": out.join("\n") };
}

const EMITTERS = {
  rust: emitRust,
  typescript: emitTs,
  python: emitPython,
  go: emitGo,
  // Future client emitters can add dart, ruby, java, csharp, php, or elixir here.
};

// --- run ---------------------------------------------------------------------

export function build() {
  const types = loadTypes();
  const files = {};
  for (const emit of Object.values(EMITTERS)) Object.assign(files, emit(types));
  return files;
}
export { loadTypes, pascal, oneLine, refName, isStringEnum, enumTypeName, collectEnums };

function main() {
  const check = process.argv.includes("--check");
  let files;
  try { files = build(); }
  catch (e) {
    if (e instanceof GenError) { console.error(`error: ${e.message}`); process.exit(2); }
    throw e;
  }
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(genDir, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
      if (cur !== content) { console.error(`drift: ${rel}`); drift++; }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && drift) { console.error(`${drift} file(s) out of date — run: node src/generate.mjs`); process.exit(1); }
  if (check) console.log("generated files up to date");
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
